version: '3.7'
services:
  flask:
   build: .
   container_name: e8_in_docker
   image: digitalocean.com/flask-python
   restart: unless-stopped
   environment:
    - PORT=5000
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - DB_NAME=e8
    - NSQ_HOST=nsqd
    - NSQ_PORT=4151
    - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/e8
   command: bash -c "alembic upgrade head && gunicorn -w 4 -b 0.0.0.0:5000 api:app"
   ports:
     - "5000:5000"
   depends_on:
     - redis
     - postgres
     - nsqd
     - worker
   links:
     - postgres
     - nsqlookupd
     - nsqd
     - worker

  worker:
    build:
      context: .
      dockerfile: _celery/Dockerfile
    user: nobody
    environment:
      - NSQ_HOST=nsqd
      - NSQ_PORT=4151
    links:
      - redis
      - nsqd
    depends_on:
      - redis
      - nsqd
    volumes:
        - .:/app

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  redis:
    image: redis:latest
    container_name: redis-e8
    ports:
      - 6379:6379
    command: redis-server

  postgres:
    image: postgres:latest
    container_name: flask-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e8
    ports:
       - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
    driver: local