"""initial migration

Revision ID: 068474a9c0d3
Revises: d12b7d52aa8e
Create Date: 2020-10-16 10:03:12.937369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068474a9c0d3'
down_revision = 'd12b7d52aa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
