"""initial migration

Revision ID: 1e172bdc9ec0
Revises: 
Create Date: 2020-10-13 18:04:11.462643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e172bdc9ec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('words_count', sa.Integer(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('tasks',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('task_status', sa.Enum('NOT_STARTED', 'PENDING', 'FINISHED', name='taskstatus'), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('results')
    # ### end Alembic commands ###
