"""initial migration

Revision ID: 683f83455955
Revises: fc94cb9bbf91
Create Date: 2020-10-16 11:09:36.169618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683f83455955'
down_revision = 'fc94cb9bbf91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
