"""initial migration

Revision ID: 9ffb7f368dc8
Revises: 683f83455955
Create Date: 2020-10-16 11:12:14.539744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffb7f368dc8'
down_revision = '683f83455955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
