"""initial migration

Revision ID: b8bbefaf26c2
Revises: f3d07df5cca0
Create Date: 2020-10-16 10:43:25.662446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bbefaf26c2'
down_revision = 'f3d07df5cca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
