"""initial migration

Revision ID: d12b7d52aa8e
Revises: f3916d0fee13
Create Date: 2020-10-14 14:10:26.590616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12b7d52aa8e'
down_revision = 'f3916d0fee13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
