"""add precipitation

Revision ID: f3916d0fee13
Revises: 1e172bdc9ec0
Create Date: 2020-10-14 05:46:06.910554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3916d0fee13'
down_revision = '1e172bdc9ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
