"""initial migration

Revision ID: f3d07df5cca0
Revises: 068474a9c0d3
Create Date: 2020-10-16 10:10:15.455157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d07df5cca0'
down_revision = '068474a9c0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
