"""initial migration

Revision ID: fc94cb9bbf91
Revises: 563200615385
Create Date: 2020-10-16 10:46:29.897976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc94cb9bbf91'
down_revision = '563200615385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_stat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_stat')
    # ### end Alembic commands ###
